site_name: KU-WIKI
site_description: æ–½å·¥ä¸­
site_author: KU informatics

theme:
  name: material
  favicon: img/favicon.ico

nav:
  - Home: index.md
  - ğŸ“…å…¬å…±è®¢é˜…æ—¥å†: misc/ğŸ“…å…¬å…±è®¢é˜…æ—¥å†.md
  - å¦‚ä½•æ°é¥­: 
    - å¦‚ä½•æ°é¥­ç®€ä»‹: eat/index.md
  - é‡‘ï¼: 
    - é‡‘ç®€ä»‹: finance/index.md
    - CardGPT: finance/CardGPT.md
  - ç§‘ç ”: 
    - ç§‘ç ”ç®€ä»‹: academic/index.md
    - åŒ»ç–—æƒ…æŠ¥å­¦ç ”ç©¶å®¤: academic/ç¤¾ä¼šæƒ…æŠ¥å­¦/åŒ»ç–—æƒ…æŠ¥å­¦ç ”ç©¶å®¤.md
  - FAQ: misc/FAQ.md
  - About: about.md