site_name: KyotoU-Chinese-Students-Wiki
site_description: 京都大学中文学生指南 | 签证、研究、生活实用信息库
site_url: https://minamotoorin.github.io/KU-WIKI/
site_author: KyotoU informatics

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - tables
  - footnotes
  - admonition
  - pymdownx.details
  - def_list
  - meta

plugins:
  - search:
      lang: zh

nav:
  - Home: index.md
  - 快速指南: practical.md
  - 入学时间表: misc/timeline.md
  - 实用信息:
    - 签证与在留资格: visa.md
    - 住宿指南: housing.md
    - 健康与医疗: medical.md
  - 公共订阅日历: misc/公共订阅日历.md
  - 金!:
    - 金简介: finance/index.md
    - CardGPT: finance/CardGPT.md
  - 科研:
    - 科研简介: academic/index.md
    - 专攻与研究室:
      - 知能情报学专攻:
        - 专攻简介: academic/Intelligence_Science_Technology/index.md
        - 研究室:
          - 语言媒体处理研究室: academic/Intelligence_Science_Technology/言語メディア処理.md
          - 语音媒体研究室: academic/Intelligence_Science_Technology/音声メディア.md
          - 视觉媒体研究室: academic/Intelligence_Science_Technology/視覚メディア.md
          - 人类扩展信息研究室: academic/Intelligence_Science_Technology/人間拡張情報.md
          - 文本媒体研究室: academic/Intelligence_Science_Technology/テキストメディア.md
          - 生命信息学研究室: academic/Intelligence_Science_Technology/生命情報学.md
      - 社会情报学专攻:
        - 专攻简介: academic/Social_Informatics/index.md
        - 研究室:
          - 分布式信息系统研究室: academic/Social_Informatics/分散情報システム.md
          - 信息社会研究室: academic/Social_Informatics/情報社会論.md
          - 信息图书馆研究室: academic/Social_Informatics/情報図書館学.md
          - 信息教育环境研究室: academic/Social_Informatics/情報教育環境.md
          - 信息安全研究室: academic/Social_Informatics/情報セキュリティ.md
          - 市场与组织信息研究室: academic/Social_Informatics/市場組織情報論.md
          - 医疗信息学研究室: academic/Social_Informatics/医療情報学.md
      - 先端数理科学专攻: academic/Advanced_Mathematical_Sciences/index.md
      - 数理工学专攻: academic/Applied_Mathematics_Physics/index.md
      - 系统科学专攻: academic/Systems_Science/index.md
      - 通信情报系统专攻: academic/Communications_Computer_Engineering/index.md
  - 友情链接: links.md
  - FAQ: misc/FAQ.md
  - About: about.md
