backend:
  name: github
  repo: minamotooRin/KU-WIKI
  branch: main
  base_url: https://decap-oauth.netlify.app

media_folder: "docs/assets/images"
public_folder: "/assets/images"

collections:
  - name: "guides"
    label: "指南文档"
    folder: "docs"
    create: true
    extension: "md"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}

  - name: "academic"
    label: "科研"
    folder: "docs/academic"
    create: true
    extension: "md"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}

  - name: "finance"
    label: "金融"
    folder: "docs/finance"
    create: true
    extension: "md"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}

  - name: "misc"
    label: "杂项"
    folder: "docs/misc"
    create: true
    extension: "md"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "内容", name: "body", widget: "markdown"}
